# Terragrunt root configuration, included by every unit in live/.
# Demonstrates:
#   - generate blocks (provider.tf, versions.tf, backend.tf, stack_meta.tf)
#   - path_relative_to_include() driving both the state key AND generated file content
#   - a tag convention passed down to modules as inputs (local-provider analogue of AWS default_tags)

locals {
  # Convention tags, mirrored from the org's root.hcl pattern. With local/random providers there is no
  # provider-level default_tags, so we inject these into modules as inputs instead (see live/* inputs).
  default_tags = {
    "owner:team"          = "platform"
    "owner:team:email"    = "devops@example.com"
    "iac:name"            = "terraform+terragrunt+terramate"
    "managed:via:project" = "terramate-terragrunt-terraform-demo"
    "backup"              = "false"
  }
}

# --- Local backend, keyed by the unit's path relative to this root.hcl -----------------
# path_relative_to_include() => "live/foundation", "live/application", "live/reporting".
# State is written under <repo>/.local-state/<relative-path>/terraform.tfstate (gitignored).
remote_state {
  backend = "local"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite"
  }
  config = {
    path = "${get_repo_root()}/.local-state/${path_relative_to_include()}/terraform.tfstate"
  }
}

# --- Terraform required version + providers -------------------------------------------
generate "versions" {
  path      = "versions.tf"
  if_exists = "overwrite"
  contents  = <<EOF
terraform {
  required_version = ">= 1.5"
  required_providers {
    random = {
      source  = "hashicorp/random"
      version = ">= 3.0"
    }
    local = {
      source  = "hashicorp/local"
      version = ">= 2.0"
    }
  }
}
EOF
}

# --- Provider configuration -----------------------------------------------------------
generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite"
  contents  = <<EOF
provider "random" {}
provider "local" {}
EOF
}

# --- Demonstration of path_relative_to_include() INSIDE generated content -------------
# Terragrunt evaluates the ${...} interpolation at parse time, so each unit gets a different value.
generate "stack_meta" {
  path      = "stack_meta.tf"
  if_exists = "overwrite"
  contents  = <<EOF
# Generated by Terragrunt. Value is unique per unit, derived from path_relative_to_include().
locals {
  terragrunt_relative_path = "${path_relative_to_include()}"
}

output "stack_path" {
  description = "Path of this unit relative to root.hcl, injected via a Terragrunt generate block."
  value       = local.terragrunt_relative_path
}
EOF
}

# Empty root inputs; units add their own.
inputs = {}
