# Terragrunt root configuration, included by every unit under live/.
# Follows the terramate-terragrunt-infrastructure-live-example pattern:
#   live/<account>/account.hcl → region.hcl → env.hcl via find_in_parent_folders().
# See: https://github.com/terramate-io/terramate-terragrunt-infrastructure-live-example

locals {
  account_vars     = read_terragrunt_config(find_in_parent_folders("account.hcl"))
  region_vars      = read_terragrunt_config(find_in_parent_folders("region.hcl"))
  environment_vars = read_terragrunt_config(find_in_parent_folders("env.hcl"))

  account_name  = local.account_vars.locals.account_name
  aws_region    = local.region_vars.locals.aws_region
  environment   = local.environment_vars.locals.environment
  tenancy       = try(local.account_vars.locals.tenancy, "unknown")
  customer_name = try(local.account_vars.locals.customer_name, "")

  # Convention tags injected into modules as inputs (local-provider analogue of AWS default_tags).
  default_tags = merge(
    {
      "owner:team"          = "platform"
      "owner:team:email"    = "devops@example.com"
      "iac:name"            = "terraform+terragrunt+terramate"
      "managed:via:project" = "terramate-terragrunt-terraform-demo"
      "tenancy"             = local.tenancy
      "region"              = local.aws_region
      "account"             = local.account_name
    },
    local.customer_name != "" ? { "customer" = local.customer_name } : {},
  )
}

# --- Local backend, keyed by the unit's path relative to this root.hcl -----------------
remote_state {
  backend = "local"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite"
  }
  config = {
    path = "${get_repo_root()}/.local-state/${path_relative_to_include()}/terraform.tfstate"
  }
}

generate "versions" {
  path      = "versions.tf"
  if_exists = "overwrite"
  contents  = <<EOF
terraform {
  required_version = ">= 1.5"
  required_providers {
    random = {
      source  = "hashicorp/random"
      version = ">= 3.0"
    }
    local = {
      source  = "hashicorp/local"
      version = ">= 2.0"
    }
  }
}
EOF
}

generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite"
  contents  = <<EOF
provider "random" {}
provider "local" {}
EOF
}

generate "stack_meta" {
  path      = "stack_meta.tf"
  if_exists = "overwrite"
  contents  = <<EOF
# Generated by Terragrunt. Value is unique per unit, derived from path_relative_to_include().
locals {
  terragrunt_relative_path = "${path_relative_to_include()}"
  account_name             = "${local.account_name}"
  aws_region               = "${local.aws_region}"
  environment              = "${local.environment}"
  tenancy                  = "${local.tenancy}"
}

output "stack_path" {
  description = "Path of this unit relative to root.hcl, injected via a Terragrunt generate block."
  value       = local.terragrunt_relative_path
}

output "stack_metadata" {
  description = "Account/region/env metadata baked in from parent account.hcl, region.hcl, and env.hcl."
  value = {
    account_name = local.account_name
    aws_region   = local.aws_region
    environment  = local.environment
    tenancy      = local.tenancy
  }
}
EOF
}

inputs = merge(
  local.account_vars.locals,
  local.region_vars.locals,
  local.environment_vars.locals,
)
