name: _terraform-fmt
on:
  workflow_call:
    inputs:
      working-dir:
        type: string
        default: "modules"

jobs:
  fmt-check:
    runs-on: ubuntu-latest
    name: terraform fmt ${{ inputs.working-dir }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea53d8efaa4189211918 # v4.2.2
      - uses: ./.github/actions/setup-asdf
      - run: terraform fmt -check -recursive ${{ inputs.working-dir }}
